feat(http): Configure the express server with PORT and HOST env vars
hertzg/tesseract-server pull request #52
Opened 2022-03-26 10:52 UTC by f9n

When we want the [Tesseract Server](https://github.com/hertzg/tesseract-server) to run on [Heroku](https://www.heroku.com), this hard-coded port and host are causing the problem.

[Heroku: Deploying Nodejs](https://devcenter.heroku.com/articles/deploying-nodejs#specifying-a-start-script)

2022-03-26 12:14 UTC, hertzg requested changes
Hello thanks for the PR, I'd be happy to merge if we can also make this a cli arg first with env changing the default value. 

I'm curious if this project would even work on heroku :think:, how do you provide the tesseract executable there?

The precendence could be as follows (later ones overwrite the previous ones):

* Default values (`8884` and `0.0.0.0`)
* `process.env.PORT` & `process.env.HOST` as default values for the cli `args`
* `--http.listen.port` &  `--http.listen.address`

2022-03-26 12:14 UTC, hertzg commented on src/providers/http/index.ts
> +      const srv = this.app.listen(PORT, HOST, () => {
Please expose these as cli args `argv['http.listen.port']` and `argv['http.listen.address']`.

2022-03-26 12:14 UTC, hertzg commented on src/providers/http/index.ts
> +const HOST = process.env.HOST || '0.0.0.0';
The `process.env.HOST` and `process.env.PORT` could be used as `default` values for the `http.listen.port` and `http.listen.address` in `../../argv`.

2022-03-26 13:01 UTC, f9n commented on src/providers/http/index.ts
> +const HOST = process.env.HOST || '0.0.0.0';
```javascript
      'http.listen.address': {
        description: 'Set http listen address',
        default: process.env.HOST,
        type: 'string',
      },
      'http.listen.port': {
        description: 'Set http listen port',
        default: process.env.PORT,
        type: 'number',
      },
```

Is this valid? When environment variables 'HOST' and 'PORT' are not defined, I think we should use another default variable.

Like this:

```javascript
const _port = parseInt(process.env.PORT || '');
const HTTP_LISTEN_PORT = Number.isInteger(_port) ? _port : 8884;

...
      'http.listen.address': {
        description: 'Set http listen address',
        default: process.env.HOST || '0.0.0.0',
        type: 'string',
      },
      'http.listen.port': {
        description: 'Set http listen port',
        default: HTTP_LISTEN_PORT,
        type: 'number',
      },
...
```

I don't know `yargs` package. When we just use this `process.env.PORT || 8884` code is not working.

On 'this.app.listen()' section shows the type error for port variable.

2022-03-26 13:09 UTC, f9n commented
I found a few solutions on StackOverflow :)

When we just set this variable, it works. 
```
TESSDATA_PREFIX=/app/.apt/usr/share/tesseract-ocr/4.00/tessdata
```

I will send Pull Request for this as soon as possible. 👍 

Check out my fork in [here](https://github.com/f9n/tesseract-server#heroku)

[Heroku App Link](https://tesseract-4-all-langs-example.herokuapp.com/)

2022-03-26 16:26 UTC, hertzg commented on src/providers/http/index.ts
> +const HOST = process.env.HOST || '0.0.0.0';
We only need to check if the value is null or undefined to use the default, Otherwise we just need to coalesce the passed value.

```
      'http.listen.address': {
        description: 'Set http listen address',
        default: process.env.HOST != null ? process.env.HOST : '0.0.0.0',
        type: 'string',
      },
      'http.listen.port': {
        description: 'Set http listen port',
        default: process.env.PORT != null ? Number(process.env.PORT) : 8884,
        type: 'number',
      },
```

2022-03-26 16:32 UTC, hertzg commented on src/argv/yargs.ts
> +
See suggestion in a [comment above](https://github.com/hertzg/tesseract-server/pull/52#discussion_r835782601)

2022-03-26 16:40 UTC, hertzg commented
> [Heroku App Link](https://tesseract-4-all-langs-example.herokuapp.com/)

Seems to be failing with missing training data errors when submitting an image.

2022-03-26 17:35 UTC, f9n commented
I am sorry. The reason for the error may be that `deu` training language data is not installed. I just installed 'eng' and 'tur' data for testing. 

```bash
$ ls /app/.apt/usr/share/tesseract-ocr/4.00/tessdata
configs          osd.traineddata  tessconfigs
eng.traineddata  pdf.ttf          tur.traineddata
```

2022-03-26 18:04 UTC, f9n commented
Maybe we can dynamically show these languages.

If we expose languages on /status endpoint with `tesseract --list-langs` command output. In index.html, we request this endpoint with javascript instead of using `ejs` like template engines.

Also, it would be nice to show the `tesseract` version on the `/status` endpoint. Maybe the `/status` endpoint is not correct for these requirements. I do not know.

```shell
$ tesseract --list-langs
List of available languages (3):
eng
osd
tur 
```

```shell
$ tesseract --version
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
```

2022-03-26 18:31 UTC, hertzg approved these changes
👏 I need to check why actions are not being run and then we can merge it :shipit:

2022-03-26 19:25 UTC, hertzg commented
> Maybe we can dynamically show these languages.
The current web ui is super simple (and ugly), so any improvements to it are very much welcome 🙏, I generally use tesseract server in docker directly from another service (without ui) hence it being ugly and barebones 🙈 .

>If we expose languages on `/status` endpoint

The status endpoint is more of a "debug" endpoint which might go away or be split into multiple sub endpoints. I generally use it to understand what's going on if something is not working as expected. So `/status` would not be the best place to show supported language information (see later quotes for suggestions).

>  with `tesseract --list-langs` command output.
Definitely! Also this command can be run only once during startup, the result cached and served from memory as it should not change much during runtime. We could expose this at `/tesseract/languages` maybe.

As a bonus there is also `tesseract --print-parameters` which could be useful to hint/autocomplete/validation of `configParams` options. Maybe at `/tesseract/options`.

```
$ tesseract --print-parameters
Tesseract parameters:
...
classify_num_cp_levels  3       Number of Class Pruner Levels
textord_dotmatrix_gap   3       Max pixel gap for broken pixed pitch
textord_debug_block     0       Block to do debug on
textord_pitch_range     2       Max range test on pitch
...
```

>  In `index.html`, we request this endpoint with vanilla javascript instead of using `ejs` like template engines.

We could, but I don't see the value of making extra http request from the client to give cached and static information 🤔.  

 
> Also, it would be nice to show the `tesseract` version on the `/status` endpoint.

For the same reason I'd probably suggest exposing such information on  `/tesseract/version` endpoint maybe. We could expose

2022-03-26 20:50 UTC, hertzg commented
I've fixed the ci issues merged latest master into your brand and also updated the readme to include correct output form help.
It seems like goss tests are now failing. @f9n Can you have a look?

2022-03-27 07:07 UTC, f9n commented
I don't know about the 'goss' tool. I think IP addresses cause failures. 🤔 

I committed new changes. I hope this works.

2022-03-30 15:57 UTC, f9n commented
Is there anything I can help with these `goss` tests? I don't understand why it broke after your commits.

2022-03-30 17:47 UTC, hertzg commented
> Is there anything I can help with these goss tests?
From just looking at it seems like it should work, but it's waiting for something to listen at that port but is not finding it before timeout. If you could look into it it would be very helpful, so far I'm struggling to find time to debug it.

> I don't understand why it broke after your commits.
It not broken on `master` it's broken on this branch and it's most likely been broken even before my commits.

2022-03-30 18:14 UTC, hertzg commented
Today I learned: If host is omitted, the server will accept connections on the [unspecified IPv6 address](https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address) (::) when IPv6 is available, or the [unspecified IPv4 address](https://en.wikipedia.org/wiki/0.0.0.0) (0.0.0.0) otherwise.

Source: https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback

Before this change `host` was ommited, and therefore with ipv6 available it was by default listening on `::`, with the explicit `host` being `0.0.0.0` it listens on ipv4 and goss_wait was looking for ipv6 bind. :man_facepalming:. 

Anyway merging this once green.

2022-03-30 18:15 UTC, merged

2022-03-30 19:29 UTC, hertzg commented
Released in `v2.5.0` thanks for the great work @f9n :raised_hands: