feat(deploy): Support heroku deployment method
hertzg/tesseract-server pull request #53
Opened 2022-03-26 14:53 UTC by f9n

Depends on: https://github.com/hertzg/tesseract-server/pull/52

2022-04-05 20:55 UTC, hertzg commented
Hello @f9n Thanks for the PR (again). Don't you think heroku deployment guide would be better as a guide linked from README instead of including this as part of the project?

We could make a section in Readme with `## Deployment Guides` and create a link to `docs/heroku-deploy.md` with the instructions? WDYT? :thinking:

2022-04-09 09:34 UTC, f9n commented
Hello. It makes sense. Thanks for your responses. 👍

2022-04-09 13:12 UTC, hertzg requested changes

2022-04-09 13:12 UTC, hertzg commented on Aptfile
> +# https://stackoverflow.com/questions/66087588/tesseract-error-while-loading-shared-libraries-libarchive-so-13-python
Would you mind inlining these files contents into the `heroku-deploy.md`?

2022-04-09 13:12 UTC, hertzg commented on Procfile
> +web: yarn run build && yarn run run
Seems like an invalid command :thinking: 

Also 

> Would you mind inlining these files contents into the `heroku-deploy.md`

2022-04-25 12:21 UTC, f9n commented on Procfile
> +web: yarn run build && yarn run run
I think this is not a problem because my Heroku app works fine.

2022-04-25 21:26 UTC, merged

2022-04-25 21:26 UTC, hertzg commented
Thansk for the updates @f9n merged. 🎉